require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ElementsController do

  # This should return the minimal set of attributes required to create a valid
  # Element. As you add validations to Element, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all elements as @elements" do
      element = Element.create! valid_attributes
      get :index
      assigns(:elements).should eq([element])
    end
  end

  describe "GET show" do
    it "assigns the requested element as @element" do
      element = Element.create! valid_attributes
      get :show, :id => element.id
      assigns(:element).should eq(element)
    end
  end

  describe "GET new" do
    it "assigns a new element as @element" do
      get :new
      assigns(:element).should be_a_new(Element)
    end
  end

  describe "GET edit" do
    it "assigns the requested element as @element" do
      element = Element.create! valid_attributes
      get :edit, :id => element.id
      assigns(:element).should eq(element)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Element" do
        expect {
          post :create, :element => valid_attributes
        }.to change(Element, :count).by(1)
      end

      it "assigns a newly created element as @element" do
        post :create, :element => valid_attributes
        assigns(:element).should be_a(Element)
        assigns(:element).should be_persisted
      end

      it "redirects to the created element" do
        post :create, :element => valid_attributes
        response.should redirect_to(Element.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved element as @element" do
        # Trigger the behavior that occurs when invalid params are submitted
        Element.any_instance.stub(:save).and_return(false)
        post :create, :element => {}
        assigns(:element).should be_a_new(Element)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Element.any_instance.stub(:save).and_return(false)
        post :create, :element => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested element" do
        element = Element.create! valid_attributes
        # Assuming there are no other elements in the database, this
        # specifies that the Element created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Element.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => element.id, :element => {'these' => 'params'}
      end

      it "assigns the requested element as @element" do
        element = Element.create! valid_attributes
        put :update, :id => element.id, :element => valid_attributes
        assigns(:element).should eq(element)
      end

      it "redirects to the element" do
        element = Element.create! valid_attributes
        put :update, :id => element.id, :element => valid_attributes
        response.should redirect_to(element)
      end
    end

    describe "with invalid params" do
      it "assigns the element as @element" do
        element = Element.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Element.any_instance.stub(:save).and_return(false)
        put :update, :id => element.id, :element => {}
        assigns(:element).should eq(element)
      end

      it "re-renders the 'edit' template" do
        element = Element.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Element.any_instance.stub(:save).and_return(false)
        put :update, :id => element.id, :element => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested element" do
      element = Element.create! valid_attributes
      expect {
        delete :destroy, :id => element.id
      }.to change(Element, :count).by(-1)
    end

    it "redirects to the elements list" do
      element = Element.create! valid_attributes
      delete :destroy, :id => element.id
      response.should redirect_to(elements_url)
    end
  end

end
